apiVersion: v1
kind: Service
metadata:
  name: proxy
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: customerProxy
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address-count: "1"
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address: {{ config.customer.ipPLS }}
    service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
    service.beta.kubernetes.io/azure-pls-visibility: "*"
    service.beta.kubernetes.io/azure-pls-auto-approval: "{{ config.customer.subscription }}"
spec:
  selector:
    app: proxy
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 3128
    targetPort: 3128
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: ajoergensen/tinyproxy
        env:
        - name: ALLOWED
          value: "{{config.customer.vnetAddressPrefix}}"
        - name: LISTEN_PORT
          value: "3128"
        livenessProbe:
          exec:
            command: 
            - /bin/true
          initialDelaySeconds: 5
          periodSeconds: 150
        readinessProbe:
          exec:
            command:
            - /bin/true
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - containerPort: 3128
#     http_proxy=127.0.0.1:3128 curl ifconfig.me
#     http_proxy=proxy:3128 curl ifconfig.me
#     http_proxy=10.2.128.100:3128 curl ifconfig.me
