apiVersion: v1
kind: Service
metadata:
  name: proxy
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-pls-create: "true"
    service.beta.kubernetes.io/azure-pls-name: providerApp
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address-count: "1"
    service.beta.kubernetes.io/azure-pls-ip-configuration-ip-address: {{ config.provider.ipPLS }}
    service.beta.kubernetes.io/azure-pls-proxy-protocol: "false"
    service.beta.kubernetes.io/azure-pls-visibility: "*"
    service.beta.kubernetes.io/azure-pls-auto-approval: "{{ config.provider.subscription }}"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        network: filter
    spec:
      containers:
      - name: proxy
        image: nginx
        ports:
        - containerPort: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: default-deny-egress
# spec:
#   podSelector: {}
#   policyTypes:
#   - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-network-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      network: filter
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 10.2.128.100/32
            # except:
            # - 10.0.0.0/8
      # ports:
        # - protocol: TCP
        #   port: 3128


